### PR TITLE
User-friendly API for both single and multi CRS dataset

### PR DESCRIPTION
**Pull request by benbovy**
@scottyhq I’ve been thinking more about single vs. multi-CRS datasets or dataarrays and I could see strong arguments in favor of either one or the other (I’ll open an issue for general discussion on this topic).

So in this PR I’ve tried to reconcile both views through an API that hopefully looks straightforward (I've also tried to avoid too complex internal logic).

There's an example notebook [here](https://github.com/benbovy/xproj/blob/ebaeb1c515b4da69531384b14b5bedefdedccee4/examples/single_vs_multi_crs.ipynb).

The main idea is to provide both direct access via the proj accessor (e.g., `ds.proj.crs`) and explicit access by passing a CRS-indexed coordinate name (e.g., `ds.proj("spatial_ref").crs`). In the case of a multi-CRS dataset, any direct access attempt raises a user-friendly error message.

Leaving aside general opinions about single vs. multi-CRS datasets, any thoughts about the API proposed here?

### CODE REVIEW

**Comment by benbovy** [comment]
> I’ll open an issue for general discussion on this topic

See #2.

**Comment by scottyhq** [comment]
> Leaving aside general opinions about single vs. multi-CRS datasets, any thoughts about the API proposed here? 

I added a comments on the issues, but restating here that I'm pro single-CRS :) and the following seems good to me!
```python 
ds_wgs84 = ds.proj.assign_crs(spatial_ref="epsg:4326")
ds_wgs84.proj.crs
```

**Comment by benbovy** [comment]
I think the explicit access `ds_wgs84.proj("spatial_ref").crs` is a useful alternative even if we enforce single-CRS.

Regarding static-typing for example:

- `.proj.crs` may return either `None` or a `pyproj.crs.CRS` instance
- `.proj(...).crs` always returns a `pyproj.crs.CRS` instance

**Comment by benbovy** [comment]
This is ready for review I think.

In [ae11695](https://github.com/benbovy/xproj/pull/1/commits/ae11695b77e953dd83ccef92a3b242df973e6600) I added some code to still restrict one CRS per Dataset / DataArray. It will be easier to to remove this restriction later than the other way around.

I'll add tests in a follow-up PR.

**Comment by benbovy** [comment]
I'm going to merge this as it fixes some single CRS enforcement issues and makes things easier for later choosing between single vs. multi-CRS dataset. (I hope you don't have any objection @scottyhq)

This will allow moving forward with adding tests and more experimentation.

**Comment by scottyhq** [comment]
> This is ready for review I think. 

Sorry I missed this, looks great! Feel free to merge away. I will be more available next week if you'd like reviews on anything.

**Pull request merged**
